---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth-microservice
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
secretGenerator:
  - name: cloudsql-gcp-sa
    files:
      - cloudsql-gcp-sa.json
generatorOptions:
  disableNameSuffixHash: true
